name: ntfy_dart
description: A simple wrapper for the ntfy.sh API
version: 0.1.2
homepage: https://github.com/jr1221/ntfy_dart

environment:
  sdk: '>=2.18.2 <4.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
